spring:
  devtools:
    livereload:
      # ?? ???? ??? ?? ? ?? ????.
      enabled : true
  thymeleaf:
    # thymeleaf ?? ??
    prefix : classpath:/templates/
    suffix : .html
    # thymeleaf? ?? ??? ??? ???. cache=false ??(???? true)
    cache : false
    # templates ????? ??? ??? ??? ??, ??? ??? ?????.
    check-template-location : true

