spring:
  devtools:
    livereload:
      enabled : true
  thymeleaf:
    prefix : classpath:/templates/
    suffix : .html
    cache : false
    check-template-location : true
  datasource:
    driverClassName : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/aggregate
    username : incruit
    password : test


